<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="Test_Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script type="text/javascript" src="/App_Themes/NexusCore/Scripts/prototype.js"></script>
    <script type="text/javascript" src="/App_Themes/NexusCore/Scripts/scriptaculous.js?load=effects,builder"></script>
    <script type="text/javascript" src="/App_Themes/NexusCore/Scripts/lightbox.js"></script>
    <link rel="stylesheet" href="/App_Themes/NexusCore/lightbox.css" type="text/css"
        media="screen" />
</head>
<body>
    <form id="form1" runat="server">
    <h2>
        Simple User Interface</h2>
    <p>
        e2CMS is a powerful CMS platform offering many useful ecommerce features. The new
        revolutionary framework is component based management system. The rich interactivity,
        drag-and-drop interface is very task oriented and easies the user interaction with
        the system.
    </p>
    <p style="text-align: center;">
        <a href="/User_Files/Images/e2CMS/EasyToUse1.jpg" target="preview">
            <img alt="" src="/User_Files/Images/e2CMS/EasyToUse1_small.jpg" /></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="/User_Files/Images/e2CMS/EasyToUse2.jpg"
                target="preview">
                <img alt="" src="/User_Files/Images/e2CMS/EasyToUse2_small.jpg" /></a>
    </p>
    <h2>
        <span>Screen: Left: All components on web page are managed by drag and drop interface.
            Right: Web content manager can edit content on live site.</span></h2>
    <h2>
        Design Flexiblity</h2>
    <p>
        Create Master page without coding using our template tools and design. You can instantly
        switch page template to shape your website according to your vision. A dynamic design
        refreshes your brand, responses to customer needs and adaptive to market demands.
        e2CMS includes all the tools to help you control of your web presence and the experiences
        you deliver.</p>
    <p style="text-align: center;">
        <a href="/User_Files/Images/e2CMS/Template1.jpg" target="preview">
            <img alt="" src="/User_Files/Images/e2CMS/Template1_small.jpg" /></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="/User_Files/Images/e2CMS/Template2.jpg"
                target="preview">
                <img alt="" src="/User_Files/Images/e2CMS/Template2_small.jpg" /></a>
    </p>
    <h2>
        <span>Screen: Left: User can install multi templates and themes for their website. Right:
            very easy to switch from one to another.</span></h2>
    <h2>
        Search Engine Optimization</h2>
    <p>
        e2CMS provides tools to manage your SEO campaigns. Through an easy user-interface,
        users can edit page name, titles, descriptions and keywords. With e2CMS you will
        never worry about miss filling any Meta tags. The system would save your time by
        automatic inherited keyword and descriptions from parent tree. e2CMS enables URL
        Aliasing, which allows users create simple and readable URLs, as well as search-friendly
        URLs.</p>
    <p style="text-align: center;">
        <a href="/User_Files/Images/e2CMS/SEO1.jpg" target="preview">
            <img alt="" src="/User_Files/Images/e2CMS/SEO1_small.jpg" /></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="/User_Files/Images/e2CMS/SEO2.jpg"
                target="preview">
                <img alt="" src="/User_Files/Images/e2CMS/SEO2_small.jpg" /></a>
    </p>
    <h2>
        <span>Screen: Left: user can have global Title, Keyword and description. Right: Individual
            Title, Keyword and Description can be place for every single page and friendly URL
            are generated by system.</span></h2>
    <h2>
        Digital Asset Management</h2>
    <p>
        Easily manage and secure hundreds of text, files, movies, images, PDFs and more
        by “dragging-and-dropping” in e2CMS File Manager. You can preview your image or
        text and copy, cut or paste your online items just like manage files in your windows
        desktop.</p>
    <p style="text-align: center;">
        <a href="/User_Files/Images/e2CMS/FileManager.jpg" target="preview">
            <img alt="" src="/User_Files/Images/e2CMS/FileManager_small.jpg" /></a></p>
    <h2>
        <span>Screen: File Manager works just like windows file explorer.</span></h2>
    <h2>
        Security and Permission</h2>
    <p>
        You can use Role management to personalize and grant access to e2CMS website. It
        is very easy to create customer area within your website and grant access to specific
        user group.</p>
    <p style="text-align: center;">
        <a href="/User_Files/Images/e2CMS/Privacy.jpg" target="preview">
            <img alt="" src="/User_Files/Images/e2CMS/Privacy_small.jpg" /></a>
    </p>
    <h2>
        <span>Screen: User can review page permissions and add new role for each page and group
            of pages.</span></h2>
    <h2>
        More Functionality by Components</h2>
    <p>
        The Module Viewer provides overview of what your website can do. The more components
        installed by user the more things their website capable with. With Module Viewer
        you can check version, release date of the component you have installed and then
        decide whether to update to new version.
    </p>
    <p style="text-align: center;">
        <a href="/User_Files/Images/e2CMS/Component.jpg" target="preview">
            <img alt="" src="/User_Files/Images/e2CMS/Component_small.jpg" /></a>
    </p>
    <h2>
        <span>Screen: Website grows functionalities by install more modules, but site performance
            will never overload, all components are dynamically assembled by running time.</span></h2>
    <h2>
        Increased Productivity</h2>
    <p>
        The CMS Platform is built by .NET technology. If you are developer or you wish to
        add new customer functions in you can easily upload ASCX Web User Control and include
        them as component inside your page.</p>
    </form>
</body>
</html>
